name: Kernel Build

on: workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: 'Checkout Repo'
      uses: actions/checkout@v3
    - name: Build Kernel
      run: |
        git clone https://github.com/t2linux/linux-t2-patches.git
        cd linux-t2-patches && git checkout 18d3466c7c6eba76743e65418847357f16e11a23 && rm ./2002* && cd ..
        mkdir patches
        cp ./linux-t2-patches/*patch ./patches
        cd patches
        ls > ../linux-t2-patches/list.conf
        sed -i -e 's/^/pve\//' ../linux-t2-patches/list.conf
        cd ..
        echo "APT::Get::Assume-Yes \"true\";" > ./90forceyes
        #echo "APT::Get::force-yes \"true\";" > ./90forceyes
        
        DOCKER_IMAGE=debian:unstable
        docker pull ${DOCKER_IMAGE}
        docker run \
        --privileged \
        -t \
        -v "$(pwd)":/repo \
        ${DOCKER_IMAGE} \
        /bin/bash -c 'cd /repo && \
        cp ./90forceyes /etc/apt/apt.conf.d/90forceyes && \
        apt update && apt install devscripts debhelper equivs git && \
        git clone https://github.com/fabianishere/pve-edge-kernel && \
        cd pve-edge-kernel && \
        git checkout v5.19.x && \
        cp ../linux-t2-patches/*patch ./debian/patches/pve && \
        echo >> ./debian/patches/series.linux && \
        cat ../linux-t2-patches/list.conf >> ./debian/patches/series.linux && \
        echo "CONFIG_APPLE_BCE=m" >> ./debian/config/config.pve && \
        echo "CONFIG_APPLE_IBRIDGE=m" >> ./debian/config/config.pve && \
        echo "CONFIG_BT_HCIBCM4377=m" >> ./debian/config/config.pve && \
        cat ./debian/config/config.pve && \
        git submodule update --init --depth=1 --recursive linux && \
        git submodule update --init --recursive && \
        debian/rules debian/control && \
        mk-build-deps -i && \
        debuild -ePVE* --jobs=auto -b -uc -us'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debs
        path: "*.deb"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: "*.deb"
        tag_name: v5.19.17-1
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
