name: Kernel Build - 6.5

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    if: ${{ !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
    - name: Free up disk space for the CI
      uses: AdityaGarg8/remove-unwanted-software@v1
      with:
       remove-android: 'true'
       remove-dotnet: 'true'
       remove-haskell: 'true'
    - name: 'Checkout Repo'
      uses: actions/checkout@v3
    - name: Build Kernel
      run: |
        git clone https://github.com/t2linux/linux-t2-patches.git
        cd linux-t2-patches && git checkout bc5ec1bdf68bb88e0cbc959a611a2fc44cbdc868 #&& wget https://github.com/AdityaGarg8/T2-Ubuntu/raw/ssd/0001-bpfilter-Add-option-to-disable-logs.patch && rm 2001* && cd ..
        rm 2008* && cd ..
        #mkdir patches
        #cp ./linux-t2-patches/*patch ./patches
        #cd patches
        #ls > ../linux-t2-patches/list.conf
        #sed -i -e 's/^/pve\//' ../linux-t2-patches/list.conf
        #cd ..
        echo "APT::Get::Assume-Yes \"true\";" > ./90forceyes
        #echo "APT::Get::force-yes \"true\";" > ./90forceyes
        apt list --installed | cut -d "/" -f 1 | grep python | xargs > ./python-pkg
        for missing in python3-apport python3-commandnotfound python3-distupgrade python3-problem-report python3-update-manager python3.10-venv
        do
        sed -i -e "s/\<${missing}\>//g" ./python-pkg
        done

        DOCKER_IMAGE=debian:bookworm
        docker pull ${DOCKER_IMAGE}
        docker run \
        --privileged \
        -t \
        -v "$(pwd)":/repo \
        ${DOCKER_IMAGE} \
        /bin/bash -c 'cd /repo && \
        cp ./90forceyes /etc/apt/apt.conf.d/90forceyes && \
        apt update && apt install wget && \
        echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list && \
        wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg && \ 
        apt update && apt install asciidoc-base automake bc bison cpio debhelper dh-python file flex \
        gcc git kmod libdw-dev libelf-dev libiberty-dev libnuma-dev libslang2-dev libssl-dev libtool lintian lz4 dwarves libpve-common-perl python3-dev zstd \
        perl-modules rsync sed sphinx-common tar xmlto zlib1g-dev && \
        #apt-get install $(cat ./python-pkg) && \
        git clone https://git.proxmox.com/git/pve-kernel.git && \
        cd pve-kernel && \
        cp ../linux-t2-patches/*patch ./patches/kernel && \
        cp ../T2.patch ./ && \
        git config --global user.email "example@example.com" && \
        git config --global user.name "Example Example" && \
        git am T2.patch && \
        #echo >> ./debian/patches/series.linux && \
        #cat ../linux-t2-patches/list.conf >> ./debian/patches/series.linux && \
        #cat ../linux-t2-patches/extra_config >> ./debian/config/config.pve && \
        #git submodule update --init --depth=1 --recursive linux && \
        #git submodule update --init --recursive && \
        #debian/rules debian/control && \
        #mk-build-deps -i && \
        KERNEL_SRC_SUBMODULE=submodules/ubuntu-kernel && \
        ZFSONLINUX_SUBMODULE=submodules/zfsonlinux && \
        git submodule update --depth 1 --init ${KERNEL_SRC_SUBMODULE} && \
        git submodule update --init --recursive ${ZFSONLINUX_SUBMODULE} && \
        make deb && \
        ls -l'
        #debuild -ePVE* --jobs=auto -b -uc -us'
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: debs
        path: ${{ github.workspace }}/pve-kernel/*.deb
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/pve-kernel/*.deb
        tag_name: v6.5.11-7-t2-1
        body: |
          If you really like the work I am doing and wanna support me, consider donating here! :
          
          https://github.com/sponsors/AdityaGarg8
          
          https://www.paypal.com/paypalme/AdityaGarg8

          Your contribution shall be appreciated and be used in my education!
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
